### PR TITLE
Feature/component placement on breadboard

### PR DESCRIPTION
**Pull request by gupta-arpit**
https://github.com/frg-fossee/eSim-Cloud/issues/169

### CODE REVIEW

**Comment by gupta-arpit** [comment]
Demo

Component-placement

**Comment by firuza** [comment]
Great Arpit, however, when the component is placed on the breadboard and then dragged,  rather than keeping it connected (using wires) can have it have it disconnected from the breadboard. I mean depicting a physical board and component. When you pull a component off the board, it's no longer connected. Let me know what you think about it. Thanks.

**Comment by gupta-arpit** [comment]
Yes, that should be the way ideally.

The current resistors can't be placed in one go. Because of their incompatible size, the first leg needs to be placed first following by the second leg. But this issue should be solved by making the resistor's size compatible with the breadboard instead of altering the breadboard's behavior.

Will make the relevant changes to the breadboard. Maybe, we can open another issue to fix the resistor then?

**Comment by gupta-arpit** [comment]
@firuza pushed the changes. can you check now?

Component

**Comment by nagsides** [comment]
@gupta-arpit : Yes, will check it soon and shall also create a new issue for resistor.

**Comment by firuza** [comment]
Thanks. This is fine 

1. After placing the component on the breadboard and instead of moving it, you delete it, then the breadboard points still remain filled with black color. 
2. Apart from resistor, I also had minor issues with placing potentiometer, slideswitch, and temperature sensor. Shall raise issues for them too. 
3. Placing components on the first two lines or the last two lines of the breadboard will lead to short circuit on the physical breadboard. We may have to raise another issue for addressing this.

**Comment by gupta-arpit** [comment]
Sure @firuza 
will look into these issues and get back.

**Comment by firuza** [comment]
@gupta-arpit Thanks. Can you also check whether there is any lag while placing LCD on the breadboard. Other components seem to be fine but LCD has a lot of lag in my case. I have not used the zoom feature. It gets connected though.

**Pull request merged**
