### PR TITLE
Enhancements/replacing browser alert

### PR DESCRIPTION
**Pull request by gupta-arpit**

### CODE REVIEW

**Comment by firuza** [comment]
There seems to be some issue with the pull request:

1. Clicking on 'Save temporary' button should show 'Done Saved'. But, there is no popup.
2. Clicking on 'Save on Cloud' button should show 'Saved'. But there is no popup.
3. Click on either of the above buttons multiple times should show 'Done updating' and 'Updated' respectively. But, there is no popup and it creates copies of the circuit which can be seen in the dashboard.

**Comment by gupta-arpit** [comment]
Will look into it

**Comment by gupta-arpit** [comment]
Can you check now?

**Comment by firuza** [comment]
Thanks Arpit,

> There seems to be some issue with the pull request:
> 
> 1. Clicking on 'Save temporary' button should show 'Done Saved'. But, there is no popup. **(Working now)**
> 2. Clicking on 'Save on Cloud' button should show 'Saved'. But there is no popup. **(Working now)**
> 3. Click on either of the above buttons multiple times should show 'Done updating' and 'Updated' respectively. But, there is no popup and it creates copies of the circuit which can be seen in the dashboard. **(Working now)**

4. Delete circuit (on cloud or temporary): The message, 'Are You Sure You want to Delete Circuit' is shown as browser alert instead of using alert service.
5. Most of the alerts are working fine as expected. However, I had a query. I have not been able to test 'negative test cases' i.e. alert messages like 'failed to load from gallery', 'something went wrong', 'Error Occurred for Ofline Circuit (Private Window Can be a Reason)'. How does one test these? 
6. Just another query (no action needed from your side): Say, when you save the project, the save button gets highlighted with a gray round box, which still remains even after the action is completed. If you click anywhere else, it is no longer highlighted. This is true for some other buttons too (export file, view component list). This was not the case earlier. Any idea why?

Apart from the above 2 issues (4 and 5), this pull request is good to go.

**Comment by gupta-arpit** [comment]
Hey @firuza 

4. Pushed the confirm modal component. Should work fine now
5. You can force throw an error in the specific parts of the code and test?
6. Not able to reproduce this. Could you send a screenshot maybe?

**Comment by firuza** [comment]
> Hey @firuza
> 
> 4. Pushed the confirm modal component. Should work fine now **(Will confirm by tomorrow)**
> 5. You can force throw an error in the specific parts of the code and test? **(ok)**
> 6. Not able to reproduce this. Could you send a screenshot maybe? **(Gif file below)**
gray_highlight_circle

**Pull request merged**
